wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1661969925.057629
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 45
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 45
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.2
      8:
      - 5
batch_size:
  desc: null
  value: 256
checkpoint_path:
  desc: null
  value: checkpoints/Flax_CIFAR_100_Supervised/Final_Flax_CIFAR_100_Supervised10001
data_path:
  desc: null
  value: CIFAR-100/
dataset_args:
  desc: null
  value:
    brightness: 0.4
    color_jitter_prob: 0.6
    contrast: 0.4
    crop_size: 32
    gaussian_prob: 0.5
    gray_scale_prob: 0.2
    horizontal_flip_prob: 0.5
    hue: 0.1
    max_scale: 0.9
    min_scale: 0.4
    saturation: 0.2
log:
  desc: null
  value: true
log_n_val_steps:
  desc: null
  value: 69
name:
  desc: null
  value: Flax_CIFAR_100_Supervised
steps:
  desc: null
  value: 10001
val_dataset_args:
  desc: null
  value:
    brightness: 0.4
    color_jitter_prob: 0
    contrast: 0.4
    crop_size: 32
    gaussian_prob: 0
    gray_scale_prob: 0
    horizontal_flip_prob: 0.5
    hue: 0.1
    max_scale: 1
    min_scale: 0.9
    saturation: 0.2
val_steps:
  desc: null
  value: 70
workers:
  desc: null
  value: 1
