wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1661703549.42791
    t:
      1:
      - 1
      - 5
      - 9
      - 12
      - 40
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 12
      - 40
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.2
      8:
      - 5
batch_size:
  desc: null
  value: 256
checkpoint:
  desc: null
  value: false
checkpoint_path:
  desc: null
  value: null
data_path:
  desc: null
  value: CIFAR-100/
dataset_args:
  desc: null
  value:
    brightness: 0.4
    color_jitter_prob: 0.6
    contrast: 0.4
    crop_size: 32
    gaussian_prob: 0.5
    gray_scale_prob: 0.2
    horizontal_flip_prob: 0.5
    hue: 0.1
    max_scale: 0.9
    min_scale: 0.4
    saturation: 0.2
dist_url:
  desc: null
  value: tcp://localhost:40000
gpus:
  desc: null
  value: 1
job_id:
  desc: null
  value: 0
log:
  desc: null
  value: true
log_n_steps:
  desc: null
  value: 800
log_n_train_steps:
  desc: null
  value: 100
log_n_val_steps:
  desc: null
  value: 69
lr:
  desc: null
  value: 0.001
name:
  desc: null
  value: CIFAR_100_Supervised
rank:
  desc: null
  value: 0
steps:
  desc: null
  value: 10001
val_dataset_args:
  desc: null
  value:
    brightness: 0.4
    color_jitter_prob: 0
    contrast: 0.4
    crop_size: 32
    gaussian_prob: 0
    gray_scale_prob: 0
    horizontal_flip_prob: 0.5
    hue: 0.1
    max_scale: 1
    min_scale: 0.9
    saturation: 0.2
val_steps:
  desc: null
  value: 70
warmup_steps:
  desc: null
  value: 200
wd:
  desc: null
  value: 1.5e-06
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: -1
